spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true

  profiles:
    include: oauth
server:
  servlet:
    encoding:
      force-response: true
